apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: seu-apim
  annotations:
    azure.workload.identity/client-id: "ea75c595-d978-4682-9f6d-612a014c68ba" # "YOUR_IDENTITY_CLIENT_ID"