apiVersion: v1
kind: ConfigMap
metadata:
  name: seu-apim-config
  namespace: seu-apim
data:
  # Django Configuration
  DEBUG: "False"
  ALLOWED_HOSTS: "py.seu.edu.sa,172.199.93.190,localhost,127.0.0.1,*.seu.edu.sa,172.25.*,172.25.10.101"
  DJANGO_SETTINGS_MODULE: "APIM.settings"

  CORS_ALLOW_ALL_ORIGINS: "False"

  # External Service URLs
  YAQEEN_BASE_URL: "http://p-hq-yaqin-web.seu.net/api/student"
  NOOR_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/Education/MOEStudentRecord/4.0/SchoolStudentRecordService.svc"
  NOOR_SOAP_ACTION: "http://tempuri.org/ISchoolStudentRecordService/GetLastSchoolCertificate"
  DISABILITY_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/SocialAffairs/MOSADisabilityReport/DisabilityReportService.svc"
  DISABILITY_SOAP_ACTION: "http://tempuri.org/IDisabilityReportService/GetDisabilityInfo"
  SOCIAL_SECURITY_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/SocialAffairs/MOSAIndigentInquiry/IndigentInquiryService.svc"
  SOCIAL_SECURITY_SOAP_ACTION: "http://tempuri.org/IIndigentInquiryService/GetIndigentdByNationalId"
  MOAHAL_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/Education/MOEQualifications/3.0/QualificationsService.svc"
  MOAHAL_SOAP_ACTION: "http://tempuri.org/IQualificationsService/GetQualifications"
  QIYAS_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/Education/QiyasExamResult/4.0/QiyasExamResultsService.svc"
  QIYAS_SOAP_ACTION: "http://tempuri.org/IQiyasExamResultsService/GetExamResult"
  NATIONAL_ADDRESS_SOAP_ENDPOINT: "http://10.4.80.25/GSBExpress/Communication/Post/SPWaselAddress/WaselAddressService.svc"
  NATIONAL_ADDRESS_SOAP_ACTION: "http://tempuri.org/IWaselAddressService/GetIndividualWaselAddress"

  # ERP Configuration
  ATS_ERP_TEST_GATEWAY_URL: "https://erpapi.seu.edu.sa"
  ATS_ERP_TEST_API_KEY_NAME: "x-api-key"
  ATS_ERP_PROD_GATEWAY_URL: "https://apiservicesprod.seu.edu.sa"
  ATS_ERP_PROD_API_KEY_NAME: "x-api-key"
  EJADAH_ERP_URL: "http://t-hq-erpuat-app.seu.net:8000"
  EJADAH_ERP_USERNAME: "IH_EJADA"

  # SMS Gateway
  SMS_GATEWAY_USER: "SEU"
  SMS_GATEWAY_SENDER_ID: "SEU"
  SMS_GATEWAY_URL: "https://www.msegat.com/gw/sendsms.php"

  # Database Configurations (non-sensitive parts)
  NoorDB_host: "172.30.2.39\\sqllive02"
  NoorDB_database: "GHDB-Master"
  NoorDB_username: "Addmission"
  NoorDB_charset: "utf8"
  NoorDB_prefix: ""
  NoorDB_prefix_indexes: "true"
  NoorDB_trust_server_certificate: "true"

  BANNER_DB_PROTOCOL: "TCP"
  BANNER_DB_HOST: "172.30.2.30"
  BANNER_DB_PORT: "1521"
  BANNER_DB_SERVICE_NAME: "pprd"
  BANNER_DB_USER: "zalshaikh"
  BANNER_DB_ENABLED: "True"

  # Azure OpenAI
  AZURE_OPEN_AI_ENDPOINT: "https://shiekh.openai.azure.com/"
  AZURE_OPEN_AI_MODEL_NAME: "gpt-4.1"
  AZURE_OPEN_AI_API_VERSION: "2024-12-01-preview"
  AZURE_OPEN_AI_API_DEPLOYMENT: "gpt-4.1"

    # MSSQL Database Configuration
  DB_ENGINE: "mssql"
  DB_NAME: "apimanager"
  DB_HOST: "172.30.2.39"
  DB_PORT: "1424"
  DB_OPTIONS_DRIVER: "ODBC Driver 18 for SQL Server"
  DB_OPTIONS_TRUST_SERVER_CERTIFICATE: "true"
  DB_OPTIONS_ENCRYPT: "false"
  DB_INSTANCE: "SQLLIVE01_AG"
