apiVersion: v1
kind: Secret
metadata:
  name: seu-apim-secrets
  namespace: seu-apim
type: Opaque
data:
  # Django Secret Key
  django-secret-key: "ZWIhc19eZXV2ITMldWRhNDA1dSh6LSYtbiE1NjViIW0mcGsyOHlkIXY2eTcqIyE="
  
  # Database URL - FIXED (URL-encoded password)
  database-url: "cG9zdGdyZXNxbDovL3NldV90b29sc191c2VyOlNldXBhc3MxMjNAcGctYXBpbS1ha3MtZGIwMS5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9zZXVfdG9vbHNfZGI/c3NsbW9kZT1yZXF1aXJl"
  
  # External service credentials
  yaqeen-username: "eWFxZWVubmlu"
  yaqeen-password: "WUBxMzNOJFQmQCQzdQ=="
  sms-gateway-key: "NWU5OTg3MTZiYjgwM2M5MDM0ZTA1NGQzMjU5YjVjZmY="
  azure-openai-key: "NUhkOHRDNHQ5cmpKOG1yck1oZ0tUYzZqSzIzQndBRHdUUGdGamxmcTJvWTR2TDMzWXlWa0pRUUo5OUJHQUNmaE1rNVhKM3czQUFBQkFDT0dCcWF6"
  
  # ERP API Keys
  ats-erp-test-api-key: "TUdCN0gyTFg5MERNTFI4TjE3QllBSjRNVDhYVFpaUFNDUDBCSzFKV0xPM1VPTVlERDIw"
  ats-erp-prod-api-key: "VTNOUko1Wk9UVVNUUDc3T1ZEUVhJUDNUMThWUFNWMkxYUTlPS0hBQVVISFZEUUwwSlY="
---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-secrets
  namespace: seu-apim
type: Opaque
data:
  ejadah-password: "MTIzNDU2Nzg="
  noordb-password: "c2V1QGFkMzIx"
  banner-db-password: "U2V1QDEyMzQ1Ng=="